# Generated by Django 2.2.3 on 2019-10-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('adress', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('fix', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, default='gesstock/provider-icon.png', upload_to='gesstock/')),
            ],
        ),
    ]
