# Generated by Django 2.2.3 on 2019-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0002_auto_20191025_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('fix', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, default='gesstock/provider-icon.png', upload_to='gesstock/')),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, default='gesstock/customer-icon.png', upload_to='gesstock/'),
        ),
    ]
