# Generated by Django 2.2.3 on 2019-10-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0004_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
