# Generated by Django 2.2.3 on 2019-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0007_article_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
