# Generated by Django 2.2.3 on 2019-10-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0009_auto_20191026_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('procurementDate', models.DateField()),
                ('received', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gesstock.Article')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gesstock.Provider')),
            ],
        ),
    ]
