# Generated by Django 2.2.3 on 2019-10-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0010_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
