# Generated by Django 2.2.3 on 2019-10-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0012_auto_20191026_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementitem',
            name='procurementDate',
        ),
        migrations.RemoveField(
            model_name='procurementitem',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='procurementitem',
            name='received',
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procurementDate', models.DateField()),
                ('received', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gesstock.Provider')),
            ],
        ),
    ]
