# Generated by Django 2.2.3 on 2019-10-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0013_auto_20191026_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementitem',
            name='article',
        ),
        migrations.DeleteModel(
            name='Procurement',
        ),
        migrations.DeleteModel(
            name='ProcurementItem',
        ),
    ]
