# Generated by Django 2.2.3 on 2019-10-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0016_delivery_deliveryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='article',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryItem',
        ),
    ]
