# Generated by Django 2.2.3 on 2019-10-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0018_delivery_deliveryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, default='gesstock/provider-icon.png', upload_to='gesstock/'),
        ),
    ]
