# Generated by Django 2.2.3 on 2019-07-20 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('profil_img', models.ImageField(default='static/uploads/employee/default.png', upload_to='static/uploads/employee/')),
                ('birth_date', models.DateField()),
                ('birth_to', models.CharField(max_length=50)),
                ('regis_number', models.CharField(max_length=20)),
                ('cni', models.CharField(max_length=20)),
                ('cni_img', models.ImageField(null=True, upload_to='static/uploads/employee/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single')], max_length=10, null=True)),
                ('nomber_children', models.IntegerField(default=0, null=True)),
                ('social_security_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('STAGE', 'STAGE')], max_length=10)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('contract_doc', models.ImageField(null=True, upload_to='static/uploads/employee/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Post')),
            ],
        ),
    ]
