# Generated by Django 2.2.3 on 2019-07-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='nomber_children',
            new_name='number_children',
        ),
    ]
