# Generated by Django 2.2.3 on 2019-07-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190720_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
