# Generated by Django 2.2.3 on 2019-07-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20190721_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cni_img',
            field=models.ImageField(default='default_cni.jpg', upload_to='static/uploads/employee/'),
            preserve_default=False,
        ),
    ]
