# Generated by Django 2.2.3 on 2019-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_cni_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profil_img',
            field=models.ImageField(default='uploads/employee/default.png', upload_to='uploads/employee/'),
        ),
    ]
