# Generated by Django 2.2.3 on 2019-07-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190721_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profil_img',
            field=models.ImageField(default='static/uploads/employee/default.png', upload_to='static/uploads/employee/'),
        ),
    ]
