# Generated by Django 2.2.3 on 2019-07-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20190721_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profil_img',
            field=models.ImageField(default='uploads/employee/default.png', upload_to='uploads/employee/'),
        ),
    ]
