# Generated by Django 2.2.3 on 2019-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20190722_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profil_img',
            field=models.ImageField(default='employee/default.png', upload_to='employee/'),
        ),
    ]
