# Generated by Django 2.2.3 on 2019-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20190722_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='fix',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='tel',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
