# Generated by Django 2.2.3 on 2019-07-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20190722_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sexe',
            field=models.CharField(blank=True, choices=[('H', 'HOMME'), ('F', 'FEMME')], max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'married'), ('single', 'single')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number_children',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profil_img',
            field=models.ImageField(blank=True, default='employee/default.png', upload_to='employee/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
