# Generated by Django 2.2.3 on 2019-07-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190722_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_doc',
            field=models.ImageField(null=True, upload_to='employee/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'HOMME'), ('W', 'FEMME')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
