# Generated by Django 2.2.3 on 2019-07-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_diploma_professionalexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='year',
            field=models.ImageField(upload_to=''),
        ),
    ]
