# Generated by Django 2.2.3 on 2019-07-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20190725_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='year',
            field=models.IntegerField(),
        ),
    ]
