# Generated by Django 2.2.3 on 2019-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_salarydesignation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydesignation',
            name='base',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarydesignation',
            name='nbr_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydesignation',
            name='patronal_deduction',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarydesignation',
            name='patronal_rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarydesignation',
            name='salary_deduction',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarydesignation',
            name='salary_gain',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarydesignation',
            name='salary_rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='code',
            field=models.IntegerField(),
        ),
    ]
