# Generated by Django 2.2.3 on 2019-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_auto_20190829_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydesignation',
            name='base',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='patronal_deduction',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='salary_deduction',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='salary_gain',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
    ]
