# Generated by Django 2.2.3 on 2019-08-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_auto_20190829_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydesignation',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='patronal_deduction',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='patronal_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='salary_deduction',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='salary_gain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salarydesignation',
            name='salary_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
