# Generated by Django 2.2.3 on 2019-09-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_auto_20190830_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('nbr_hour', models.IntegerField(default=0)),
                ('base', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('salary_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('salary_gain', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('salary_deduction', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('patronal_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('patronal_deduction', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Salary')),
            ],
        ),
    ]
