# Generated by Django 2.2.3 on 2019-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_auto_20190905_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydesignation',
            name='nbr_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
