# Generated by Django 2.2.3 on 2019-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_auto_20190911_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
