# Generated by Django 2.2.3 on 2019-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_salary_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
