# Generated by Django 2.2.3 on 2019-11-14 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoiceitem_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Account'),
        ),
    ]
