# Generated by Django 2.2.3 on 2019-11-14 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_auto_20191114_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='account',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='accounting.Account'),
            preserve_default=False,
        ),
    ]
