# Generated by Django 2.2.3 on 2019-11-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_auto_20191114_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Account'),
        ),
    ]
