# Generated by Django 2.2.3 on 2019-11-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_auto_20191114_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='account',
        ),
    ]
