# Generated by Django 2.2.3 on 2019-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_remove_invoiceitem_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='bla',
            field=models.IntegerField(default=12),
        ),
    ]
