# Generated by Django 2.2.3 on 2019-11-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_invoiceitem_bla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='bla',
        ),
    ]
