# Generated by Django 2.2.3 on 2019-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.CharField(blank=True, default='dashboard', max_length=20, null=True),
        ),
    ]
