# Generated by Django 2.2.3 on 2019-11-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivingFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='archiving.ArchivingFolder')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='archiving/')),
                ('parentFolder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archiving.ArchivingFolder')),
            ],
        ),
    ]
