# Generated by Django 2.2.3 on 2019-11-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivingfile',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
