# Generated by Django 2.2.3 on 2019-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0002_archivingfile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivingfile',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
