# Generated by Django 2.2.3 on 2019-08-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('account_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('solde', models.IntegerField()),
                ('document', models.FileField(null=True, upload_to='accounting/')),
                ('type_operation', models.CharField(choices=[('DEBIT', 'débiter'), ('credit', 'crediter')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Account')),
            ],
        ),
    ]
