# Generated by Django 2.2.3 on 2019-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_operation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='accounting/'),
        ),
    ]
