# Generated by Django 2.2.3 on 2019-11-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gesstock', '0019_auto_20191028_1515'),
        ('accounting', '0004_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gesstock.Customer'),
        ),
        migrations.AddField(
            model_name='operation',
            name='provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gesstock.Provider'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Account'),
        ),
    ]
